// <auto-generated />
using System;
using ICC.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ICC.Api.Migrations
{
    [DbContext(typeof(ICCDbContext))]
    [Migration("20240313155754_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ICC.Api.Entities.PersonalAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Residents")
                        .HasColumnType("TEXT");

                    b.Property<int>("Square")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PersonalAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountNum = "1_2024_AB",
                            Address = "103132, г. Москва, Ивановская площадь",
                            EffectiveDate = new DateTime(2024, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpirationDate = new DateTime(2027, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Residents = " ",
                            Square = 277000
                        });
                });

            modelBuilder.Entity("ICC.Api.Entities.Resident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<int>("PersonalAccountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAccountId");

                    b.ToTable("Residents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "eva@gmail.com",
                            FirstName = "Ева",
                            LastName = "Кернс",
                            PersonalAccountId = 1
                        });
                });

            modelBuilder.Entity("ICC.Api.Entities.Resident", b =>
                {
                    b.HasOne("ICC.Api.Entities.PersonalAccount", "PersonalAccount")
                        .WithMany()
                        .HasForeignKey("PersonalAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalAccount");
                });
#pragma warning restore 612, 618
        }
    }
}
